pipeline {
    agent any

    tools {
        jdk 'jdk11'
        maven 'maven3'
    }

    stages {

        stage('Git Checkout from Github SCM') {
            steps {
                git 'https://github.com/rakeshsguttedar/BoardgameListingWebApp.git'
            }
        }

        stage('Compile') {
            steps {
                sh "mvn compile"
            }
        }

        stage('Package') {
            steps {
                sh "mvn clean package"
            }
        }

        stage('Install') {
            steps {
                sh "mvn install"
            }
        }

    }

}
